### ISSUE TITLE
Violations of use

### ISSUE THREAD

**Issue by JacobBrandt** [spectriclabs/elastic_datashader#1]
I think you should remove this repository.  Everything about this repository is in violation of the Elastic License.  I would advise you to carefully read Section 2 of that license.

You can't make a portion of the Elastic License code available publicly (all those tar files in kibana and tile_layer.js).  You can copy the repository which is basically a fork and that can be public since it will contain the Elastic License Agreement and contain the entire source as-is.  Furthermore you cannot really do anything with this repository as it's against the license to be deployed in any environment as it contains derivative works.

Other's will claim that they thought this was Elastic License code because the file headers of your new code that you have interleaved with Elastic is claiming them to be but that argument will be fallacious as anyone who reads the License can clearly tell this is not Elastic code that the repository is claiming.

This is a cool thing you have done.  I'm just trying to ensure that you are aware of the many violations in this repo and what the license says about people that breach section 2.

> A breach or threatened breach, by You of Section 2 may cause
  irreparable harm for which damages at law may not provide adequate relief, and
  therefore Elastic shall be entitled to seek injunctive relief without being
  required to post a bond

**Comment by maihde** [comment]
Hi @JacobBrandt.  

We appreciate you bringing this to our attention and we will investigate and resolve accordingly.

- I agree that the headers in the JavaScript files need to be changed; this was an oversight.
- Is it of your opinion that a public 'fork' of an Elastic repository can include modifications to code covered by the Elastic license?  Or must all public 'forks' keep any code under the Elastic license as-is?

Beyond a doubt, the Python code in this repository is _not_ in violation of the Elastic license under any interpretation.
