### ISSUE TITLE
Datashader Kibana Layer Bug - Resolved In Newer Kibana Version

### ISSUE THREAD

**Issue by mkellogg91** [spectriclabs/elastic_datashader#13]
Creating this issue by request.

in Kibana Version 7.10.* if you setup a datashader layer:
If you type invalid KQL in the search bar (i.e. ‘())’) it crashes the map

when testing this in version 7.13 - 8.0 the error was caught and no longer crashed the map.

**Comment by mkellogg91** [comment]
leaving this issue as open just so that it is more easily visible

**Comment by ballenspectric** [comment]
Are there still 7.10 instances being used on related projects?  It looks like this repo's latest branch uses 7.13.2.

**Comment by ballenspectric** [comment]
Closing this issue as we are now targeting much newer versions.  Can re-open if necessary.
