### ISSUE TITLE
Toggle of "Show ellipses" causes ellipse color change which no longer aligns with legend

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#14]
Steps to reproduce:
Add Datashader layer to Map
Layer Style section
Color : By Value
Observe legend is correct for plot points.
In Layer Style section change the "Render Mode" of "Show ellipses" to "on".
Observe ellipse colors do not align with legend colors.

**Comment by mkellogg91** [comment]
I'm not able to reproduce this. When switching on the show ellipses mode I see no difference. I'm using the test flight sample data, I'm assuming in order to see this issue I need to use something else?
