### ISSUE TITLE
Update for Kibana 7.17

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#18]

**Comment by ndmitch311** [comment]
Initial commit: https://github.com/spectriclabs/kibana/commit/875a3b5713a7a4b6c9d8ed7b84809e906949c934

**Comment by ndmitch311** [comment]
Changed title / request from 7.15.2 to 7.16.2

**Comment by ndmitch311** [comment]
Changed title/request to 7.17. Changes made for 7.16 were pulled into 7.17 build with no issue. There is an outstanding issue that the URL set in config is not being pulled into the UI, but this will be tested further when 7.17 is deployed to the test environment.

**Comment by ballenspectric** [comment]
See https://github.com/spectriclabs/kibana/tree/feat-datashader-7.17.1

**Comment by ballenspectric** [comment]
> Build 40 - Layer Style/Color "By Value" Value does not persist when selected.

This was resolved in the 7.17 branch in 0095091a2ca8d3e8b98cb12afd1f164b166e5fa8
