### ISSUE TITLE
Global filters not working for Datashader layer

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#29]
AC-110
Datashader layer Filtering section, unable to toggle options to: 
-Apply global filter to layer data
-Apply global time to layer data

**Comment by ndmitch311** [comment]
https://github.com/spectriclabs/kibana/tree/feat-datashader-7.13.2

https://github.com/spectriclabs/kibana/tree/feat-datashader-7.17.1

**Comment by ballenspectric** [comment]
Resolved for the 7.17 branch in 9dc342fc7b6961f86f255cfc18f071db52a4a8fb
