### ISSUE TITLE
Add DATASHADER_ELASTIC_API_KEY environment variable

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#32]
Add DATASHADER_ELASTIC_API_KEY environment variable and if the variable is set, tack on "Authorization: ApiKey..." header to each request.

**Comment by ballenspectric** [comment]
Added in 5b6b79035e67c1f30c3ee6c70f8e992c2eb6373b

**Comment by ndmitch311** [comment]
Feature has been provided to requesting group. Closing issue.
