### ISSUE TITLE
Upgrade to Python 3.11

### ISSUE THREAD

**Issue by ballenspectric** [spectriclabs/elastic_datashader#36]
We are still running on Python 3.9.  Supposedly Python 3.11 benchmarks about 20% faster.  Note that Python 3.10 and greater require OpenSSL 1.1.1.

**Comment by ballenspectric** [comment]
The numba package does not support Python 3.11 yet.

**Comment by desean1625** [comment]
looks like Python 3.11 is supported by numba now.

**Comment by desean1625** [comment]
looks like georgio needs to support 3.11

**Comment by desean1625** [comment]
completed
