### ISSUE TITLE
ellipse mode doesn't work if the major/minor/tilt fields are indexed as numbers but published to JSON as strings

### ISSUE THREAD

**Issue by maihde** [spectriclabs/elastic_datashader#7]
Currently datashader uses the `source` values when rendering ellipses.  The problem is that the source values are kept as the original type, regardless of how the data was indexed.

At a minimum, datashader should call `float(x)` on these values.  Ideally, datashader would be modified to use Elastic docvalues instead.

**Comment by ballenspectric** [comment]
Was this addressed by f92328377d61939f9d045e93c22ba224ca36caf6?

**Comment by ballenspectric** [comment]
This appears to be fixed.  Can re-open if necessary.
