### ISSUE TITLE
Error when filter string contains "#"

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#8]
When filtering against field with values that include "#" datashader could not render layer. 
Example: "#1234 -- Brown Fox"
When the query criteria was changed to "*Fox" datashader rendered/returned results with no errors.

The following errors were seen. (List is not exhaustive.)
JSONDecodeError('Unterminated string starting at line 1 column 236 (char 235'))
JSONDecodeError('Unterminated string starting at line 1 column 491 (char 490'))
JSONDecodeError('Unterminated string starting at line 1 column 728 (char 727'))

**Comment by ndmitch311** [comment]
@maihde This issue is resolved in the application using datashader, but I'm not seeing any changes to datashader itself to resolve the issue. Do you  have insight?

**Comment by desean1625** [comment]
I do not see this error either. I am going to close this out.
