### ISSUE TITLE
Feature: support asynchronous loading of tiles

### ISSUE THREAD

**Issue by ndmitch311** [spectriclabs/elastic_datashader#9]
It would improve the Kibana user experience if a tile request returned immediately while the lengthy tile generation process continued.

**Comment by ballenspectric** [comment]
Kibana's Mapbox GL fetches tiles using a pool of workers, and assumes that tile generation is quick.  But with Datashaders, tiles can take 10-30 seconds to render.  Ideally a temporary "loading" tile would be returned immediately to free up workers to respond to other web requests.  After a short wait, Mapbox GL would then re-request the tile to get the rendered version.

**Comment by ballenspectric** [comment]
There are also known bugs with cache control in Mapbox GL: https://github.com/spectriclabs/kibana/blob/bbe80cc4a1e363bf6f087261090166b73ed101e9/x-pack/plugins/maps/public/connected_components/mb_map/mb_map.tsx#L245

**Comment by ballenspectric** [comment]
This has been ported to FastAPI and appears to be working.  It is ready for more in-depth user testing.  See https://github.com/spectriclabs/elastic_datashader/tree/issues/9

**Comment by ballenspectric** [comment]
@desean1625 made some fixes in 4b620ec60a9a1607b11d6d7e955cc34b88e4d301, and this appears to be working.
